lengthIsland: 4
widthIsland: 6
cycleDuration: 1000
stopOnTimeout: True
gameDuration: 60000
unviableWeight: 0.5
chanceToGetEat:
  "Wolf":
    "Horse": 10
    "Deer": 15
    "Rabbit": 60
    "Mouse": 80
    "Goat": 60
    "Sheep": 70
    "WildBoar": 15
    "Buffalo": 10
    "Duck": 40
  "Boa":
    "Fox": 15
    "Rabbit": 20
    "Mouse": 40
    "Duck": 10
  "Fox":
    "Rabbit": 70
    "Mouse": 90
    "Duck": 60
    "Caterpillar": 40
  "Bear":
    "Boa": 80
    "Horse": 40
    "Deer": 80
    "Rabbit": 80
    "Mouse": 90
    "Goat": 70
    "Sheep": 70
    "WildBoar": 50
    "Buffalo": 20
    "Duck": 10
  "Eagle":
    "Fox": 10
    "Rabbit": 90
    "Mouse": 90
    "Duck": 80
  "Horse":
    "Plant": 100
  "Deer":
    "Plant": 100
  "Rabbit":
    "Plant": 100
  "Mouse":
    "Caterpillar": 90
    "Plant": 100
  "Goat":
    "Plant": 100
  "Sheep":
    "Plant": 100
  "WildBoar":
    "Mouse": 90
    "Caterpillar": 90
    "Plant": 100
  "Buffalo":
    "Plant": 100
  "Duck":
    "Caterpillar": 90
    "Plant": 100
  "Caterpillar":
    "Plant": 100
creaturesCommonSpecs:
  "Wolf":
    "name": "–í–æ–ª–∫"
    "icon": üê∫
    "weight": 50
    "maxCountSpecies": 30
    "maxSpeedToLocation": 3
    "amountFoodToSatiate": 8
    "satiety": 8
  "Boa":
    "name": "–£–¥–∞–≤"
    "icon": üêç
    "weight": 15
    "maxCountSpecies": 30
    "maxSpeedToLocation": 1
    "amountFoodToSatiate": 3
    "satiety": 3
  "Fox":
    "name": "–õ–∏—Å–∞"
    "icon": ü¶ä
    "weight": 8
    "maxCountSpecies": 30
    "maxSpeedToLocation": 2
    "amountFoodToSatiate": 2
    "satiety": 2
  "Bear":
    "name": "–ú–µ–¥–≤–µ–¥—å"
    "icon": üêª
    "weight": 500
    "maxCountSpecies": 5
    "maxSpeedToLocation": 2
    "amountFoodToSatiate": 80
    "satiety": 80
  "Eagle":
    "name": "–û—Ä–µ–ª"
    "icon": ü¶Ö
    "weight": 6
    "maxCountSpecies": 20
    "maxSpeedToLocation": 3
    "amountFoodToSatiate": 1
    "satiety": 1
  "Horse":
    "name": "–õ–æ—à–∞–¥—å"
    "icon": üêé
    "weight": 400
    "maxCountSpecies": 20
    "maxSpeedToLocation": 4
    "amountFoodToSatiate": 60
    "satiety": 60
  "Deer":
    "name": "–û–ª–µ–Ω—å"
    "icon": ü¶å
    "weight": 300
    "maxCountSpecies": 20
    "maxSpeedToLocation": 4
    "amountFoodToSatiate": 50
    "satiety": 50
  "Rabbit":
    "name": "–ö—Ä–æ–ª–∏–∫"
    "icon": üêá
    "weight": 2
    "maxCountSpecies": 150
    "maxSpeedToLocation": 2
    "amountFoodToSatiate": 0.45
    "satiety": 0.45
  "Mouse":
    "name": "–ú—ã—à—å"
    "icon": üêÅ
    "weight": 0.05
    "maxCountSpecies": 500
    "maxSpeedToLocation": 1
    "amountFoodToSatiate": 0.01
    "satiety": 0.01
  "Goat":
    "name": "–ö–æ–∑–∞"
    "icon": üêê
    "weight": 60
    "maxCountSpecies": 140
    "maxSpeedToLocation": 3
    "amountFoodToSatiate": 10
    "satiety": 10
  "Sheep":
    "name": "–û–≤—Ü–∞"
    "icon": üêë
    "weight": 70
    "maxCountSpecies": 140
    "maxSpeedToLocation": 3
    "amountFoodToSatiate": 15
    "satiety": 15
  "WildBoar":
    "name": "–ö–∞–±–∞–Ω"
    "icon": üêó
    "weight": 400
    "maxCountSpecies": 50
    "maxSpeedToLocation": 2
    "amountFoodToSatiate": 50
    "satiety": 50
  "Buffalo":
    "name": "–ë—É–π–≤–æ–ª"
    "icon": üêÉ
    "weight": 700
    "maxCountSpecies": 10
    "maxSpeedToLocation": 3
    "amountFoodToSatiate": 100
    "satiety": 100
  "Duck":
    "name": "–£—Ç–∫–∞"
    "icon": ü¶Ü
    "weight": 1
    "maxCountSpecies": 200
    "maxSpeedToLocation": 4
    "amountFoodToSatiate": 0.15
    "satiety": 0.15
  "Caterpillar":
    "name": "–ì—É—Å–µ–Ω–∏—Ü–∞"
    "icon": üêõ
    "weight": 0.01
    "maxCountSpecies": 1000
    "maxSpeedToLocation": 0
    "amountFoodToSatiate": 0.01
    "satiety": 0.01
  "Plant":
    "name": "–†–∞—Å—Ç–µ–Ω–∏–µ"
    "icon": üåø
    "weight": 1
    "maxCountSpecies": 200